server:
    port: 8081

spring:
  datasource:
    username: root
    password: root
    url: jdbc:sqlite:E:/sqlite_db/flagstone.db
    driver-class-name: org.sqlite.JDBC

mybatis:
  config-location: classpath:mybatis-config.xml
